agents:
  queue: "default"
steps:
  - label: ":docker:"
    command: |
      bash <<EOL
        VERSION=\$(cat version)
        echo "VERSION: \$VERSION"
        # docker build . -t alialhjouj/dokcer:$VERSION .
        # docker push alialhjouj/dokcer:$BUILDKITE_BUILD_NUMBER
      EOL
    plugins:
      - docker-login#v2.0.1:
          username: alialhjouj
          password-env: MY_DOCKER_LOGIN_PASSWORD
