agents:
  queue: "default"
  
steps:

  # - label: ":dev:"
  #   command:
  #    - curl -O -L https://$GITHUB_TOKEN@raw.githubusercontent.com/Ali-coder1996/pipeline/main/*.yaml

  
  - label: ":dev:"
    command: |
      # Set the GitHub repository URL
      REPO_URL="https://api.github.com/repos/Ali-coder1996/pipeline/contents/"
      echo $REPO_URL
      # Use the GitHub API to list files in the repository
      file_list=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $REPO_URL)

      # Loop through the list of files and download YAML files
      for url in $(echo "$file_list" | jq -r '.[] | select(.name | endswith(".yaml")) | .download_url')
      do
        filename=$(echo $url | awk -F'?' '{print $1}')
        echo "Downloading $filename"
        curl -O -L -H "Authorization: token $GITHUB_TOKEN" $filename
      done

    
  - label: "DEV"
    command:
      - buildkite-agent pipeline upload dev.yaml
    plugins:
      - 'uber-workflow/run-without-clone':
  - wait

  - label: "PROD"
    command:
      - buildkite-agent pipeline upload prod.yaml
    plugins:
      - 'uber-workflow/run-without-clone':
    

  # - command: "version=${cat version};docker build . -t image:$version.$BUILDKITE_BUILD_NUMBER"
  #   plugins:
  #     - docker#v5.9.0:
  #         image: "docker:latest"
  #         always-pull: true
  # - label: ":docker:"
  #   command: docker build . -t alialhjouj/dokcer:'${cat version}.$BUILDKITE_BUILD_NUMBER'
  #     # docker push alialhjouj/dokcer:$(cat version).$BUILDKITE_BUILD_NUMBER
  #   plugins:
  #     - docker-login#v2.0.1:
  #         username: alialhjouj
  #         password-env: MY_DOCKER_LOGIN_PASSWORD
  
