agents:
  queue: "default"
steps:
  - command: "buildkite-agent pipeline upload .buildkite/pipleine.yml"
steps:
  - label: ":docker:"
    command:
      - "docker build . -t alialhjouj/dokcer:$BUILDKITE_BUILD_NUMBER "
      - "docker push alialhjouj/dokcer:$BUILDKITE_BUILD_NUMBER "
    plugins:
      - docker-login#v2.0.1:
          username: alialhjouj
          password-env: MY_DOCKER_LOGIN_PASSWORD
