agents:
  queue: "default"
steps:
  - label: ":docker:"
    command:
      - "VERSION="$(cat version).$BUILDKITE_BUILD_NUMBER && docker build . -t alialhjouj/dokcer:$VERSION"
      - "docker push alialhjouj/dokcer:$BUILDKITE_BUILD_NUMBER" 
    plugins:
      - docker-login#v2.0.1:
          username: alialhjouj
          password-env: MY_DOCKER_LOGIN_PASSWORD
