agents:
  queue: "default"
  
steps:

  - label: ":dev:"
    command:
     - curl -O -L https://$GITHUB_TOKEN@raw.githubusercontent.com/Ali-coder1996/pipeline/main/dev.yaml

  - label: "Checkout Repository"
    command:
      - export REPO_NAME=$BUILDKITE_PIPELINE_SLUG
      - env
      - buildkite-agent pipeline upload dev.yaml
    plugins:
      - 'uber-workflow/run-without-clone':
    

  # - command: "version=${cat version};docker build . -t image:$version.$BUILDKITE_BUILD_NUMBER"
  #   plugins:
  #     - docker#v5.9.0:
  #         image: "docker:latest"
  #         always-pull: true
  # - label: ":docker:"
  #   command: docker build . -t alialhjouj/dokcer:'${cat version}.$BUILDKITE_BUILD_NUMBER'
  #     # docker push alialhjouj/dokcer:$(cat version).$BUILDKITE_BUILD_NUMBER
  #   plugins:
  #     - docker-login#v2.0.1:
  #         username: alialhjouj
  #         password-env: MY_DOCKER_LOGIN_PASSWORD
  
