agents:
  queue: "default"
  
steps:

  - label: ":modal: Build/Push Image"
    command:
      - buildkite-agent pipeline upload pipeline/template/docker-build.yaml

      
  - label: ":k8s: Deploy to Dev"
    command:
      - buildkite-agent pipeline upload pipeline/template/dev.yaml
  #   if: build.branch != "main"

  - wait: ~


  - label: ":k8s: Deploy to Prod"
    command:
      - buildkite-agent pipeline upload pipeline/template/prod.yaml
    block: ":rocket: Release!"
  #   if: build.branch != "main"

  - wait: ~

  - label: ":bash: CleanUp"
    command: "pipeline/script/cleanup.sh"

