agents:
  queue: "default"
  
steps:

  - label: ":modal: Build/Push Image"
    command:
      - buildkite-agent pipeline upload pipeline/template/docker-build.yaml

  - wait: ~

  - label: ":bash: CleanUp"
    command: "pipeline/script/cleanup.sh"
      
  - label: ":k8s: Deploy to Dev"
    command:
      - buildkite-agent pipeline upload pipeline/template/dev.yaml
  #   if: build.branch != "main"

  - block: ":rocket: Release! Deploy To Prod"

  - label: ":k8s: Deploy to Prod"
    command:
      - buildkite-agent pipeline upload pipeline/template/prod.yaml
    
  #   if: build.branch != "main"


