agents:
  queue: "default"
  
steps:

  - label: ":dev:"
    command: 
     
     - curl -O -L https://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@raw.githubusercontent.com/Ali-coder1996/pipeline/main/dev.yaml
     - ls -l
     - pwd

  - label: ":dev:"
    command: buildkite-agent pipeline upload dev.yaml

  # - command: "version=${cat version};docker build . -t image:$version.$BUILDKITE_BUILD_NUMBER"
  #   plugins:
  #     - docker#v5.9.0:
  #         image: "docker:latest"
  #         always-pull: true
  # - label: ":docker:"
  #   command: docker build . -t alialhjouj/dokcer:'${cat version}.$BUILDKITE_BUILD_NUMBER'
  #     # docker push alialhjouj/dokcer:$(cat version).$BUILDKITE_BUILD_NUMBER
  #   plugins:
  #     - docker-login#v2.0.1:
  #         username: alialhjouj
  #         password-env: MY_DOCKER_LOGIN_PASSWORD
  
